/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.avbravo.jmoordbjsfgenerator;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JSpinner;

public final class JmoordbJSFGeneratorVisualPanel4 extends JPanel {

    /**
     * Creates new form JSFGeneratorVisualPanel4
     */
    public JmoordbJSFGeneratorVisualPanel4() {
        initComponents();
    }

    @Override
    public String getName() {
        return "DataTable";
    }

    public JSpinner getjSpinnerDialogHeigth() {
        return jSpinnerDialogHeigth;
    }

    public void setjSpinnerDialogHeigth(JSpinner jSpinnerDialogHeigth) {
        this.jSpinnerDialogHeigth = jSpinnerDialogHeigth;
    }

    public JSpinner getjSpinnerDialogWidth() {
        return jSpinnerDialogWidth;
    }

    public void setjSpinnerDialogWidth(JSpinner jSpinnerDialogWidth) {
        this.jSpinnerDialogWidth = jSpinnerDialogWidth;
    }

    public JSpinner getjSpinnerDialogWidthRelation() {
        return jSpinnerDialogWidthRelation;
    }

    public void setjSpinnerDialogWidthRelation(JSpinner jSpinnerDialogWidthRelation) {
        this.jSpinnerDialogWidthRelation = jSpinnerDialogWidthRelation;
    }

    public JSpinner getjSpinnerRowsDataTable() {
        return jSpinnerRowsDataTable;
    }

    public void setjSpinnerRowsDataTable(JSpinner jSpinnerRowsDataTable) {
        this.jSpinnerRowsDataTable = jSpinnerRowsDataTable;
    }

    public JComboBox getjComboBoxDataTable() {
        return jComboBoxDataTable;
    }

    public void setjComboBoxDataTable(JComboBox jComboBoxDataTable) {
        this.jComboBoxDataTable = jComboBoxDataTable;
    }

    public JCheckBox getjCheckBoxDialogCustomized() {
        return jCheckBoxDialogCustomized;
    }

    public void setjCheckBoxDialogCustomized(JCheckBox jCheckBoxDialogCustomized) {
        this.jCheckBoxDialogCustomized = jCheckBoxDialogCustomized;
    }

    public JCheckBox getjCheckBoxDialogDinamyc() {
        return jCheckBoxDialogDinamyc;
    }

    public void setjCheckBoxDialogDinamyc(JCheckBox jCheckBoxDialogDinamyc) {
        this.jCheckBoxDialogDinamyc = jCheckBoxDialogDinamyc;
    }

    public JCheckBox getjCheckBoxTableScrollable() {
        return jCheckBoxTableScrollable;
    }

    public void setjCheckBoxTableScrollable(JCheckBox jCheckBoxTableScrollable) {
        this.jCheckBoxTableScrollable = jCheckBoxTableScrollable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHeigth = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxDataTable = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerRowsDataTable = new javax.swing.JSpinner();
        jCheckBoxTableScrollable = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinnerDialogWidth = new javax.swing.JSpinner();
        jSpinnerDialogWidthRelation = new javax.swing.JSpinner();
        jCheckBoxDialogDinamyc = new javax.swing.JCheckBox();
        jCheckBoxDialogCustomized = new javax.swing.JCheckBox();
        jSpinnerDialogHeigth = new javax.swing.JSpinner();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jPanel4.border.title"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jLabel12.text")); // NOI18N

        jComboBoxDataTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fields", "selectOneMenu", "class.toString()" }));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jLabel13.text")); // NOI18N

        jSpinnerRowsDataTable.setModel(new javax.swing.SpinnerNumberModel(20, 1, null, 1));

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxTableScrollable, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jCheckBoxTableScrollable.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxTableScrollable)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSpinnerRowsDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBoxDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerRowsDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxTableScrollable))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jPanel8.border.title"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jLabel15.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel16, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jLabel16.text")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel17, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jLabel17.text")); // NOI18N

        jSpinnerDialogWidth.setModel(new javax.swing.SpinnerNumberModel(450, 10, null, 1));

        jSpinnerDialogWidthRelation.setModel(new javax.swing.SpinnerNumberModel(550, 10, null, 1));

        buttonGroupHeigth.add(jCheckBoxDialogDinamyc);
        jCheckBoxDialogDinamyc.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxDialogDinamyc, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jCheckBoxDialogDinamyc.text")); // NOI18N
        jCheckBoxDialogDinamyc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDialogDinamycActionPerformed(evt);
            }
        });

        buttonGroupHeigth.add(jCheckBoxDialogCustomized);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxDialogCustomized, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel4.class, "JmoordbJSFGeneratorVisualPanel4.jCheckBoxDialogCustomized.text")); // NOI18N
        jCheckBoxDialogCustomized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDialogCustomizedActionPerformed(evt);
            }
        });

        jSpinnerDialogHeigth.setModel(new javax.swing.SpinnerNumberModel(250, 10, null, 1));
        jSpinnerDialogHeigth.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDialogDinamyc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxDialogCustomized)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDialogHeigth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDialogWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerDialogWidthRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jSpinnerDialogWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jSpinnerDialogWidthRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDialogHeigth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jCheckBoxDialogDinamyc)
                    .addComponent(jCheckBoxDialogCustomized))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxDialogDinamycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDialogDinamycActionPerformed
        jSpinnerDialogHeigth.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxDialogDinamycActionPerformed

    private void jCheckBoxDialogCustomizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDialogCustomizedActionPerformed
        jSpinnerDialogHeigth.setEnabled(true);
    }//GEN-LAST:event_jCheckBoxDialogCustomizedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupHeigth;
    private javax.swing.JCheckBox jCheckBoxDialogCustomized;
    private javax.swing.JCheckBox jCheckBoxDialogDinamyc;
    private javax.swing.JCheckBox jCheckBoxTableScrollable;
    private javax.swing.JComboBox jComboBoxDataTable;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinnerDialogHeigth;
    private javax.swing.JSpinner jSpinnerDialogWidth;
    private javax.swing.JSpinner jSpinnerDialogWidthRelation;
    private javax.swing.JSpinner jSpinnerRowsDataTable;
    // End of variables declaration//GEN-END:variables
}
