/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.avbravo.jmoordbjsfgenerator;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.xml.bind.annotation.XmlElementDecl;

public final class JmoordbJSFGeneratorVisualPanel2 extends JPanel {

    String template;

    /**
     * Creates new form JSFGeneratorVisualPanel2
     */
    public JmoordbJSFGeneratorVisualPanel2() {
        initComponents();
        DGlobal.setTemplate("");
        jTextFieldCodeTemplate.setVisible(false);
        jRadioButtonChangeTemplateYes.setSelected(DGlobal.esPrimeraEjecucion);
        jRadioButtonChangeMenuYes.setSelected(DGlobal.esPrimeraEjecucion);
        jRadioButtonChangeIndexYes.setSelected(DGlobal.esPrimeraEjecucion);


    }

    @Override
    public String getName() {
        return "Facelets";
    }

    public JRadioButton getjRadioButtonChangeIndexNo() {
        return jRadioButtonChangeIndexNo;
    }

    public void setjRadioButtonChangeIndexNo(JRadioButton jRadioButtonChangeIndexNo) {
        this.jRadioButtonChangeIndexNo = jRadioButtonChangeIndexNo;
    }

    public JRadioButton getjRadioButtonChangeIndexYes() {
        return jRadioButtonChangeIndexYes;
    }

    public void setjRadioButtonChangeIndexYes(JRadioButton jRadioButtonChangeIndexYes) {
        this.jRadioButtonChangeIndexYes = jRadioButtonChangeIndexYes;
    }

    public JRadioButton getjRadioButtonChangeMenuNo() {
        return jRadioButtonChangeMenuNo;
    }

    public void setjRadioButtonChangeMenuNo(JRadioButton jRadioButtonChangeMenuNo) {
        this.jRadioButtonChangeMenuNo = jRadioButtonChangeMenuNo;
    }

    public JRadioButton getjRadioButtonChangeMenuYes() {
        return jRadioButtonChangeMenuYes;
    }

    public void setjRadioButtonChangeMenuYes(JRadioButton jRadioButtonChangeMenuYes) {
        this.jRadioButtonChangeMenuYes = jRadioButtonChangeMenuYes;
    }

    public JRadioButton getjRadioButtonChangeTemplateNo() {
        return jRadioButtonChangeTemplateNo;
    }

    public void setjRadioButtonChangeTemplateNo(JRadioButton jRadioButtonChangeTemplateNo) {
        this.jRadioButtonChangeTemplateNo = jRadioButtonChangeTemplateNo;
    }

    public JRadioButton getjRadioButtonChangeTemplateYes() {
        return jRadioButtonChangeTemplateYes;
    }

    public void setjRadioButtonChangeTemplateYes(JRadioButton jRadioButtonChangeTemplateYes) {
        this.jRadioButtonChangeTemplateYes = jRadioButtonChangeTemplateYes;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public JTextField getjTextFieldCodeTemplate() {
        return jTextFieldCodeTemplate;
    }

    public void setjTextFieldCodeTemplate(JTextField jTextFieldCodeTemplate) {
        this.jTextFieldCodeTemplate = jTextFieldCodeTemplate;
    }

    public JLabel getjLabelTemplateSelected() {
        return jLabelTemplateSelected;
    }

    public void setjLabelTemplateSelected(JLabel jLabelTemplateSelected) {
        this.jLabelTemplateSelected = jLabelTemplateSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTemplate = new javax.swing.ButtonGroup();
        buttonGroupIndex = new javax.swing.ButtonGroup();
        buttonGroupMenu = new javax.swing.ButtonGroup();
        jPanelFacelets = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButtonizquierda_centro_derecho = new javax.swing.JToggleButton();
        jToggleButtonizquierda_derecha = new javax.swing.JToggleButton();
        jToggleButtonsuperior_centro = new javax.swing.JToggleButton();
        jToggleButtonsuperior_centro_abajo = new javax.swing.JToggleButton();
        jToggleButtonsuperior_izquierda_centro_derecha_abajo = new javax.swing.JToggleButton();
        jToggleButtonsuperior_izquierda_derecha = new javax.swing.JToggleButton();
        jToggleButtonsuperior_izquierda_derecha_abajo = new javax.swing.JToggleButton();
        jToggleButtonsuperior_izquierdo_centro_derecha = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelTemplateSelected = new javax.swing.JLabel();
        jTextFieldCodeTemplate = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jRadioButtonChangeIndexNo = new javax.swing.JRadioButton();
        jRadioButtonChangeIndexYes = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jRadioButtonChangeTemplateNo = new javax.swing.JRadioButton();
        jRadioButtonChangeTemplateYes = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButtonChangeMenuYes = new javax.swing.JRadioButton();
        jRadioButtonChangeMenuNo = new javax.swing.JRadioButton();

        jPanelFacelets.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jPanelFacelets.border.title"))); // NOI18N
        jPanelFacelets.setEnabled(false);
        jPanelFacelets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFaceletsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFaceletsMouseEntered(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jPanel2.border.title"))); // NOI18N

        jToggleButtonizquierda_centro_derecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/izquierda_centro_derecho.png"))); // NOI18N
        jToggleButtonizquierda_centro_derecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonizquierda_centro_derechoActionPerformed(evt);
            }
        });

        jToggleButtonizquierda_derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/izquierda_derecha.png"))); // NOI18N
        jToggleButtonizquierda_derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonizquierda_derechaActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_centro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_centro.png"))); // NOI18N
        jToggleButtonsuperior_centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_centroActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_centro_abajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_centro_abajo.png"))); // NOI18N
        jToggleButtonsuperior_centro_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_centro_abajoActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_izquierda_centro_derecha_abajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_izquierda_centro_derecha_abajo.png"))); // NOI18N
        jToggleButtonsuperior_izquierda_centro_derecha_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_izquierda_centro_derecha_abajoActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_izquierda_derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_izquierda_derecha.png"))); // NOI18N
        jToggleButtonsuperior_izquierda_derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_izquierda_derechaActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_izquierda_derecha_abajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_izquierda_derecha_abajo.png"))); // NOI18N
        jToggleButtonsuperior_izquierda_derecha_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_izquierda_derecha_abajoActionPerformed(evt);
            }
        });

        jToggleButtonsuperior_izquierdo_centro_derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jmoordbjsfgenerator/resources/layout/superior_izquierdo_centro_derecha.png"))); // NOI18N
        jToggleButtonsuperior_izquierdo_centro_derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsuperior_izquierdo_centro_derechaActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jLabel7.text")); // NOI18N

        jLabelTemplateSelected.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCodeTemplate.setText(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jTextFieldCodeTemplate.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButtonizquierda_centro_derecho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonizquierda_derecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsuperior_centro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsuperior_centro_abajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsuperior_izquierda_centro_derecha_abajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsuperior_izquierda_derecha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTemplateSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButtonsuperior_izquierda_derecha_abajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsuperior_izquierdo_centro_derecha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldCodeTemplate)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonizquierda_centro_derecho)
                    .addComponent(jToggleButtonizquierda_derecha)
                    .addComponent(jToggleButtonsuperior_centro)
                    .addComponent(jToggleButtonsuperior_centro_abajo)
                    .addComponent(jToggleButtonsuperior_izquierda_centro_derecha_abajo)
                    .addComponent(jToggleButtonsuperior_izquierda_derecha)
                    .addComponent(jToggleButtonsuperior_izquierda_derecha_abajo)
                    .addComponent(jToggleButtonsuperior_izquierdo_centro_derecha))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabelTemplateSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldCodeTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroupIndex.add(jRadioButtonChangeIndexNo);
        jRadioButtonChangeIndexNo.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeIndexNo, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeIndexNo.text")); // NOI18N

        buttonGroupIndex.add(jRadioButtonChangeIndexYes);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeIndexYes, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeIndexYes.text")); // NOI18N

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel18, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jLabel18.text")); // NOI18N

        jLabel23.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel23, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jLabel23.text")); // NOI18N

        buttonGroupTemplate.add(jRadioButtonChangeTemplateNo);
        jRadioButtonChangeTemplateNo.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeTemplateNo, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeTemplateNo.text")); // NOI18N

        buttonGroupTemplate.add(jRadioButtonChangeTemplateYes);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeTemplateYes, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeTemplateYes.text")); // NOI18N

        jLabel28.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel28, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jLabel28.text")); // NOI18N

        buttonGroupMenu.add(jRadioButtonChangeMenuYes);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeMenuYes, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeMenuYes.text")); // NOI18N

        buttonGroupMenu.add(jRadioButtonChangeMenuNo);
        jRadioButtonChangeMenuNo.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonChangeMenuNo, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel2.class, "JmoordbJSFGeneratorVisualPanel2.jRadioButtonChangeMenuNo.text")); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonChangeTemplateNo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonChangeTemplateYes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jRadioButtonChangeMenuNo))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonChangeIndexNo)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonChangeIndexYes)
                            .addComponent(jRadioButtonChangeMenuYes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jRadioButtonChangeTemplateNo)
                    .addComponent(jRadioButtonChangeTemplateYes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonChangeIndexYes)
                    .addComponent(jRadioButtonChangeIndexNo)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jRadioButtonChangeMenuYes)
                    .addComponent(jRadioButtonChangeMenuNo))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFaceletsLayout = new javax.swing.GroupLayout(jPanelFacelets);
        jPanelFacelets.setLayout(jPanelFaceletsLayout);
        jPanelFaceletsLayout.setHorizontalGroup(
            jPanelFaceletsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaceletsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelFaceletsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelFaceletsLayout.setVerticalGroup(
            jPanelFaceletsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFaceletsLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFacelets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFacelets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonizquierda_centro_derechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonizquierda_centro_derechoActionPerformed
        this.template = "izquierda_centro_derecho";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/izquierda_centro_derecho.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonizquierda_centro_derechoActionPerformed

    private void jToggleButtonizquierda_derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonizquierda_derechaActionPerformed
        this.template = "izquierda_derecha";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/izquierda_derecha.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonizquierda_derechaActionPerformed

    private void jToggleButtonsuperior_centroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_centroActionPerformed
        this.template = "superior_centro";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_centro.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_centroActionPerformed

    private void jToggleButtonsuperior_centro_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_centro_abajoActionPerformed
        this.template = "superior_centro_abajo";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_centro_abajo.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_centro_abajoActionPerformed

    private void jToggleButtonsuperior_izquierda_centro_derecha_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_izquierda_centro_derecha_abajoActionPerformed
        this.template = "superior_izquierda_centro_derecha_abajo";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_izquierda_centro_derecha_abajo.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_izquierda_centro_derecha_abajoActionPerformed

    private void jToggleButtonsuperior_izquierda_derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_izquierda_derechaActionPerformed
        this.template = "superior_izquierda_derecha";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_izquierda_derecha.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_izquierda_derechaActionPerformed

    private void jToggleButtonsuperior_izquierda_derecha_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_izquierda_derecha_abajoActionPerformed
        this.template = "superior_izquierda_derecha_abajo";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_izquierda_derecha_abajo.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_izquierda_derecha_abajoActionPerformed

    private void jToggleButtonsuperior_izquierdo_centro_derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsuperior_izquierdo_centro_derechaActionPerformed
        this.template = "superior_izquierdo_centro_derecha";
        jLabelTemplateSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/jsfgenerator/resources/layout/superior_izquierdo_centro_derecha.png"))); // NOI18N
        asignarTemplate(template);
    }//GEN-LAST:event_jToggleButtonsuperior_izquierdo_centro_derechaActionPerformed

    private void jPanelFaceletsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFaceletsMouseClicked
    }//GEN-LAST:event_jPanelFaceletsMouseClicked

    private void jPanelFaceletsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFaceletsMouseEntered
    }//GEN-LAST:event_jPanelFaceletsMouseEntered
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupIndex;
    private javax.swing.ButtonGroup buttonGroupMenu;
    private javax.swing.ButtonGroup buttonGroupTemplate;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTemplateSelected;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelFacelets;
    private javax.swing.JRadioButton jRadioButtonChangeIndexNo;
    private javax.swing.JRadioButton jRadioButtonChangeIndexYes;
    private javax.swing.JRadioButton jRadioButtonChangeMenuNo;
    private javax.swing.JRadioButton jRadioButtonChangeMenuYes;
    private javax.swing.JRadioButton jRadioButtonChangeTemplateNo;
    private javax.swing.JRadioButton jRadioButtonChangeTemplateYes;
    private javax.swing.JTextField jTextFieldCodeTemplate;
    private javax.swing.JToggleButton jToggleButtonizquierda_centro_derecho;
    private javax.swing.JToggleButton jToggleButtonizquierda_derecha;
    private javax.swing.JToggleButton jToggleButtonsuperior_centro;
    private javax.swing.JToggleButton jToggleButtonsuperior_centro_abajo;
    private javax.swing.JToggleButton jToggleButtonsuperior_izquierda_centro_derecha_abajo;
    private javax.swing.JToggleButton jToggleButtonsuperior_izquierda_derecha;
    private javax.swing.JToggleButton jToggleButtonsuperior_izquierda_derecha_abajo;
    private javax.swing.JToggleButton jToggleButtonsuperior_izquierdo_centro_derecha;
    // End of variables declaration//GEN-END:variables

    private void asignarTemplate(String template) {
        try {
            DGlobal.setTemplate(template);

            jTextFieldCodeTemplate.setText(template);

        } catch (Exception e) {
            DGlobal.error(e.getLocalizedMessage());
        }
    }
}
