/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.avbravo.jmoordbjsfgenerator;

import javax.swing.JPanel;
import java.io.File;
import javax.swing.JTextField;
import org.avbravo.jmoordbjsfgenerator.generales.Directorios;
import org.netbeans.api.project.ProjectUtils;
import org.openide.util.NbBundle;

public final class JmoordbJSFGeneratorVisualPanel1 extends JPanel {

    /**
     * Creates new form JSFGeneratorVisualPanel1
     */
    public JmoordbJSFGeneratorVisualPanel1() {
        initComponents();

        File dir = new File(Directorios.getDirectorioPropiedades());
        String[] ficheros = dir.list();
        /*
         * reemplaza la extension .properties por espacios en blanco
         */

        if (ficheros == null) {
            DGlobal.advertencia(NbBundle.getMessage(JmoordbJSFGeneratorWizardIterator.class, "Mensaje_NoArchivoPropiedades"));
            jTextFieldProyecto.setText("");

        }
        jTextFieldProyecto.setText(ProjectUtils.getInformation(DGlobal.getProject()).getDisplayName());
        
    }

    public JTextField getjTextFieldPatronHora() {
        return jTextFieldPatronHora;
    }

    public void setjTextFieldPatronHora(JTextField jTextFieldPatronHora) {
        this.jTextFieldPatronHora = jTextFieldPatronHora;
    }

    
    public JTextField getjTextFieldPatronFecha() {
        return jTextFieldPatronFecha;
    }

    public void setjTextFieldPatronFecha(JTextField jTextFieldPatronFecha) {
        this.jTextFieldPatronFecha = jTextFieldPatronFecha;
    }

    public JTextField getjTextFieldPatronFechaHora() {
        return jTextFieldPatronFechaHora;
    }

    public void setjTextFieldPatronFechaHora(JTextField jTextFieldPatronFechaHora) {
        this.jTextFieldPatronFechaHora = jTextFieldPatronFechaHora;
    }

    public JTextField getjTextFieldProyecto() {
        return jTextFieldProyecto;
    }

    public void setjTextFieldProyecto(JTextField jTextFieldProyecto) {
        this.jTextFieldProyecto = jTextFieldProyecto;
    }

    @Override
    public String getName() {
        //return "Step #1";
        return "Project";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProject = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPatronFecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPatronFechaHora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPatronHora = new javax.swing.JTextField();
        jTextFieldProyecto = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jLabel1.text")); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jPanel3.border.title"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jLabel10.text")); // NOI18N

        jTextFieldPatronFecha.setText(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jTextFieldPatronFecha.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jLabel9.text")); // NOI18N

        jTextFieldPatronFechaHora.setText(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jTextFieldPatronFechaHora.text")); // NOI18N
        jTextFieldPatronFechaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPatronFechaHoraActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jLabel11.text")); // NOI18N

        jTextFieldPatronHora.setText(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jTextFieldPatronHora.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPatronHora, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPatronFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(jTextFieldPatronFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPatronFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPatronFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPatronHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTextFieldProyecto.setEditable(false);
        jTextFieldProyecto.setText(org.openide.util.NbBundle.getMessage(JmoordbJSFGeneratorVisualPanel1.class, "JmoordbJSFGeneratorVisualPanel1.jTextFieldProyecto.text")); // NOI18N

        javax.swing.GroupLayout jPanelProjectLayout = new javax.swing.GroupLayout(jPanelProject);
        jPanelProject.setLayout(jPanelProjectLayout);
        jPanelProjectLayout.setHorizontalGroup(
            jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProjectLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldProyecto))
                    .addGroup(jPanelProjectLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProjectLayout.setVerticalGroup(
            jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jPanelProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPatronFechaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPatronFechaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPatronFechaHoraActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelProject;
    private javax.swing.JTextField jTextFieldPatronFecha;
    private javax.swing.JTextField jTextFieldPatronFechaHora;
    private javax.swing.JTextField jTextFieldPatronHora;
    private javax.swing.JTextField jTextFieldProyecto;
    // End of variables declaration//GEN-END:variables


}
